Fixed issue with markdown conversion
ORNL-MDF/mist pull request #6
Opened 2024-06-13 19:37 UTC by hespuck19

Fixed issue with markdown conversion. Previously used Pandoc to create pdf's from markdown, started to get an error with the mat.write_pdf(file) in the unit_tests.py. This change implements md2pdf which completes the conversion however still has issues with $math$ symbol rendering on the final pdf.

2024-06-13 20:01 UTC, stvdwtt requested changes

2024-06-14 19:29 UTC, stvdwtt commented
@hespuck19, does the new converter work for SS316L?

2024-06-14 19:48 UTC, hespuck19 commented
Yep. Still works with the change to the file path part. Did you want two test cases one with AlCu and one with SS316L?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Stephen DeWitt ***@***.***>
Sent: Friday, June 14, 2024 3:29:56 PM
To: ORNL-MDF/mist ***@***.***>
Cc: Spuck, Hope ***@***.***>; Mention ***@***.***>
Subject: Re: [ORNL-MDF/mist] Fixed issue with markdown conversion (PR #6)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@hespuck19<https://github.com/hespuck19>, does the new converter work for SS316L?

—
Reply to this email directly, view it on GitHub<https://github.com/ORNL-MDF/mist/pull/6#issuecomment-2168636049>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BGSKMTLNES6ELWZPYXUXUR3ZHNADJAVCNFSM6AAAAABJJBAEK2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRYGYZTMMBUHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-21 15:50 UTC, stvdwtt commented
@hespuck19, yes, please include both AlCu and SS316L in the test.

2024-06-21 20:31 UTC, stvdwtt approved these changes

2024-06-21 20:32 UTC, merged